spring:
  profiles:
    active: local,dev
  application:
    name: backend
  config:
    import: "optional:file:env.properties"
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  #    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.flywaydb: INFO

matrix:
  server-name: ${MATRIX_SERVER_NAME:}
  base-url: ${MATRIX_BASE_URL:http://localhost:8008}
  registration-shared-secret: ${MATRIX_REGISTRATION_SHARED_SECRET:}
