name: Backend Build 🧪

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 📄
        uses: actions/checkout@v6

      - name: Setup Java ☕
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Run backend build 🧪
        run: ./backend/gradlew -p ./backend/ build
